# Generated by Django 4.1.3 on 2022-12-16 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(db_column='Id', primary_key=True, serialize=False)),
                ('username', models.CharField(db_column='Username', max_length=100, unique=True)),
                ('password', models.TextField(db_column='Password', max_length=100)),
                ('date_created', models.DateTimeField(blank=True, db_column='Date_Created', null=True)),
                ('token', models.TextField(blank=True, db_column='Token', max_length=500, null=True)),
            ],
            options={
                'db_table': 'Users',
                'managed': False,
            },
        ),
    ]
